### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by m0nq** [zgordon/how-to-gutenberg-plugin#5]
Trying to follow your course, having a few setup issues when I run `npm i`

Wondering what version of node you're running?

```events.js:183░░░░░░⸩ ⠹ extract:esprima: sill extract buffer-xor@1.0.3
      throw er; // Unhandled 'error' event
      ^

Error: sha1-ILt0A9POo5jpHcRxCo/xuCdKJe0= integrity checksum failed when using sha1: wanted sha1-ILt0A9POo5jpHcRxCo/xuCdKJe0= but got sha1-ljRQKqEsRF3Vp8VzS1cruHOKrLs=. (8882 bytes)
    at Transform.on (~/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/ssri/index.js:275:19)
    at emitNone (events.js:111:20)
    at Transform.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
events.js:183░░░░░░⸩ ⠹ extract:electron-releases: sill extract buffer-xor@1.0.3
      throw er; // Unhandled 'error' event
      ^

Error: sha1-ILt0A9POo5jpHcRxCo/xuCdKJe0= integrity checksum failed when using sha1: wanted sha1-ILt0A9POo5jpHcRxCo/xuCdKJe0= but got sha1-ljRQKqEsRF3Vp8VzS1cruHOKrLs=. (8882 bytes)
    at Transform.on (~/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/ssri/index.js:275:19)
    at emitNone (events.js:111:20)
    at Transform.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm WARN jsforwp-blocks@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/Users/Vishnu/Downloads/Practice/IL/industriallogic.dev.cc/wp-content/plugins/how-to-gutenberg-plugin/node_modules/.staging/fsevents-78d8192f/node_modules/strip-json-comments' -> '/Users/Vishnu/Downloads/Practice/IL/industriallogic.dev.cc/wp-content/plugins/how-to-gutenberg-plugin/node_modules/.staging/strip-json-comments-f9c83c18'

npm ERR! cancel after 1 retries!

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2018-09-06T17_46_01_577Z-debug.log```

**Comment by m0nq** [comment]
I'll let you close this, but I was able to solve this by `npx create-guten-block gutenberg-plugin` and copying files over from there.

Cheers!
